/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

//servo signal pin(orange) to A0
//OLED SCK to D15 and SDA to D14

#include <stdint.h>
#include "device_drivers/timers.h"
#include "device_drivers/gpio.h"
#include "device_headers/stm32f446xx.h"
#include "device_drivers/i2c.h"
#include "device_drivers/ssd1306_new.h"




static void delay_ms(uint32_t ms)
{
    while (ms--)                      // Loop for each millisecond
    {
        for (uint32_t i = 0; i < 1000; i++)  // 1000 iterations per ms
        {
            __asm volatile ("nop");   // Do nothing for 1 cycle
        }
    }
}


volatile uint8_t TAR_ADDR = 0x3C;
volatile uint32_t ACK_NUM;
volatile uint32_t NACK_NUM;



int main(void)
{
	//Servo
	// Turn on the clock for GPIOA
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOAEN;

	// Enable I2C clock
	RCC->APB1ENR |= RCC_APB1ENR_TIM2EN;


	GPIO_Init(GPIOA, GPIO_PIN_0, GPIO_MODE_ALTERNATE,
			0,0,0);

	SelectAltFunction(GPIOA, GPIO_PIN_0, 1);

	ServoMotor_Init(20);
	////////////////////////////////////////////////////////////////////////////////////////////////////////
	//Display

	// Turn on the clock for GPIOB
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOBEN;

	// Enable I2C clock
	RCC->APB1ENR |= RCC_APB1ENR_I2C1EN;

	// I2C1_SCL PIN
	GPIO_Init(GPIOB, GPIO_PIN_8, GPIO_MODE_ALTERNATE,
			1,0,1);

	// I2C1_SDA PIN
	GPIO_Init(GPIOB, GPIO_PIN_9, GPIO_MODE_ALTERNATE,
			1,0,1);


	// ALT_FUNC SCL
	SelectAltFunction(GPIOB, GPIO_PIN_8, 4);

	// ALT_FUNC SDA
	SelectAltFunction(GPIOB, GPIO_PIN_9, 4);

	i2c_init();

	ssd1306_init();


//	ssd1306_cmd(0x21);
//		ssd1306_cmd(0);
//		ssd1306_cmd(127);
//
//		ssd1306_cmd(0x22);
//		ssd1306_cmd(0);
//		ssd1306_cmd(7);
//
//		for(int i=0;i<1024;i++)
//		{
//			ssd1306_data(0x00);
//		}
//		// 16x16 heart bitmap (2 pages × 16 columns)
//
//
//		ssd1306_cmd(0x21);
//		ssd1306_cmd(56);
//		ssd1306_cmd(71);
//
//		ssd1306_cmd(0x22);
//		ssd1306_cmd(3);
//		ssd1306_cmd(4);
//
//		const uint8_t heart[32] =
//		{
//		    // Page 3 (upper 8 pixels)
//		    0x00, 0x0C, 0x1E, 0x3F,
//		    0x7F, 0xFF, 0xFE, 0xFC,
//		    0xFC, 0xFE, 0xFF, 0x7F,
//		    0x3F, 0x1E, 0x0C, 0x00,
//			0xFF,0xFF,0xFF,0xFF,
//			0xFF,0xFF,0xFF,0xFF,
//			0xFF,0xFF,0xFF,0xFF,
//			0xFF,0xFF,0xFF,0xFF
//		};
//
//		for (int i = 0; i < 32; i++)
//		{
//		    ssd1306_data(heart[i]);
//		}



	//servo motor loop
	while(1)
	{
//	SetServoSpeed_Direction(20,slow,CW);
//	DisplayServoStatus();
//	delay_ms(1000);
//	SetServoSpeed_Direction(20,medium,CW);
//	DisplayServoStatus();
//	delay_ms(1000);
//	SetServoSpeed_Direction(20,fast,CW);
//	DisplayServoStatus();
//	delay_ms(1000);
//	SetServoSpeed_Direction(20,stop,CW);
//	DisplayServoStatus();
//	delay_ms(1500);
	SetServoSpeed_Direction(20,slow,CW);
	DisplayServoStatus();
	delay_ms(1000);
	SetServoSpeed_Direction(20,medium,CW);
	DisplayServoStatus();
	delay_ms(1000);
	SetServoSpeed_Direction(20, stop, CW);
	DisplayServoStatus();
	delay_ms(300);
	SetServoSpeed_Direction(20,fast,ACW);
	DisplayServoStatus();
	delay_ms(2000);
	SetServoSpeed_Direction(20,slow,ACW);
	DisplayServoStatus();
	delay_ms(1000);
	SetServoSpeed_Direction(20,medium,ACW);
	DisplayServoStatus();
	delay_ms(1000);
	SetServoSpeed_Direction(20,slow,ACW);
	DisplayServoStatus();
	delay_ms(1000);
	}


}
